### ISSUE TITLE
I have trouble conecting the LCD 

### ISSUE THREAD

**Issue by AriadnaDRA** [Breazile/MandoPuter#14]
Hello, I'm trying to do the Mando Puter for the beskar guantlet, but i didn't find the same display that the one show in this github.

i'm working with Adafruit Feather M4 Expres and a random LCD
![image](https://github.com/Breazile/MandoPuter/assets/133783611/61cf0104-b949-4549-a20f-0f35f462b01e)
![image](https://github.com/Breazile/MandoPuter/assets/133783611/43291b0c-c478-4c1f-9649-b3b314c55eb0)
![image](https://github.com/Breazile/MandoPuter/assets/133783611/e1b60dcd-00c5-4d49-9be7-fca26ad346a7)
and I'm not sure how to connect the different ports.
IDK if it is possible to do it with this screen...

Thanks

**Comment by Breazile** [comment]
If that display works with 3.3 volts (rather than 5v) then it should work in the beskar configuration. Select the 1.3" LCD in the configuration and wiring should be the same as this:

https://github.com/Breazile/MandoPuter/blob/master/Images/FeatherM4ExpressBeskarWiring.jpg

**Comment by Breazile** [comment]
BLK pin should be the same as LITE
RES same as RST
SCL same as SCK
SDA same as SI

**Comment by AriadnaDRA** [comment]
Thanks! i will try

**Comment by AriadnaDRA** [comment]
I tested and it seams to respond but im not able to discover why it dosent show anything

![WhatsApp Image 2023-07-10 at 8 21 25 PM](https://github.com/Breazile/MandoPuter/assets/133783611/9b152a9e-79a4-4507-b96d-c30a1aa786f2)

https://github.com/Breazile/MandoPuter/assets/133783611/47c925f3-96f9-4cfc-a789-26759435e89a


https://github.com/Breazile/MandoPuter/assets/133783611/b36328bd-f368-4fe2-94f4-9e0ea04434fc

**Comment by Breazile** [comment]
I can see there is a code error by the flashing LED. Can you send me the code.py that you are using as well as the file called boot_out.txt that should be on the Feather? That will show me which version of CircuitPython is installed on the board as well as the selections in code,py.

**Comment by AriadnaDRA** [comment]
The boot_out is this:

Adafruit CircuitPython 8.2.0 on 2023-07-05; Adafruit Feather M4 Express with samd51j19
Board ID:feather_m4_express
UID:A8F7D68E32433753202020310E180FFF

And the code.py is the same has the download via https://github.com/Breazile/MandoPuter/blob/master/Releases/ESP32-S3Beskar.zip

"""
MandoPuter will display text in a Mandalorian font on a tiny LCD display

File   - code.py
Author - Jon Breazile

https://github.com/Breazile/MandoPuter

Font credits to ErikStormtrooper, the bitmap fonts were created from his TrueType font
http://www.erikstormtrooper.com/mandalorian.htm
"""
import gc
import time
import alarm
import board
import busio
import pwmio
import neopixel
import digitalio
import displayio
import adafruit_dotstar as dotstar
import adafruit_imageload
from analogio import AnalogIn
from adafruit_display_text import label
from adafruit_bitmap_font import bitmap_font
from adafruit_st7789 import ST7789
from adafruit_lc709203f import LC709203F

"""
  ----------- User configurable items -----------

  This is where you can customize your display and hardware setup.
  Select either the Pre-Beskar (1.14" LCD) or Beskar (1.3" LCD) display.
  Some lines are commented out which means the line is not active.
  A commented line starts with a #


"""
# Set the display type
#DISPLAY        = "Pre-Beskar"          # Adafruit 1.14" LCD display  https://www.adafruit.com/product/4383
DISPLAY       = "Beskar"                # Adafruit 1.3" LCD display   https://www.adafruit.com/product/4313
DISP_BRIGHT    = 80                     # How bright to make the display - 0% to 100%

# Board being used
#BOARD_TYPE    = "ESP32-S3"             # ESP32-S3                  https://www.adafruit.com/product/5477
BOARD_TYPE    = "FeatherM4"             # Feather M4 Express        https://www.adafruit.com/product/3857
#BOARD_TYPE    = "ItsyBitsyM4"          # ItsyBitsy M4 Express      https://www.adafruit.com/product/3800
#BOARD_TYPE    = "ItsyBitsyRP2040"      # ItsyBitsy RP2040          https://www.adafruit.com/product/4888
#BOARD_TYPE     = "PiPicoRP2040"        # Raspberry Pi Pico RP2040  https://www.adafruit.com/product/4864

# Mandalorian charater sequence that is shown on the display
messages       = [ "MLM", "JBM", "SAS", "JAS", "JBM", "MLM", "SAS", "AJS", "SAS"]
# Time that each character group is shown 0.50 is 500 milliseconds, or 1/2 of a second
delays         = [  0.75,  0.75,  0.650,  0.75, 0.50,  0.84,  1.00,  0.35,  0.84]
TEXT_COLOR     = 0xFF0000               # Red on black (you can chose colors here - https://www.color-hex.com/)

# Name of the owner shown after startup and before the sequence starts
SHOW_NAME      = 1                      # Set to 1 to display the name, or 0 to not display a name
OWNER_NAME     = "Your Name Here"       # Name of the owner to be shown
NAME_COLOR     = 0x00FF00               # Green on black (you can chose colors here - https://www.color-hex.com/)
NAME_HOLD      = 3.0                    # How many seconds to display the name

# Banner graphic(s) shown after the owner's name and before the sequence starts
SHOW_IMG       = 2                      # How many images to show. 0 = no images, 1 = 1 image, 2 = 2 images
IMG1           = "TheMandalorian240.bmp"         # File name of the first 8 bit BMP graphic to be shown after each text sequence
IMG1_HOLD      = 5.00                   # How long the first image is displayed in seconds
IMG2           = "BabyYoda240.bmp"      # File name of the second 8 bit BMP graphic to be shown after the first image
IMG2_HOLD      = 5.00                   # How long the second image is displayed in seconds

# Other settings for debugging and battery monitoring
BATTERY_SZ     = 500                    # Size of battery in mAh (only for the ESP32-S3 board)
BATTERY_MON    = 0                      # Set to 1 to enable the battery monitor, 0 to disable it
LOW_BATT_LEVEL = 10                     # Show the low battery icon when the battery goes below this percentage
ENABLE_LEDS    = 0                      # Set to 1 to turn on LEDs for debugging, set to 0 to save battery
SPI_SPEED      = 48000000               # How fast the SPI bus to the LCD operates
"""
# ---------------------------------------------------------------------------------
"""

def DisplayName(name, hold, color, init_tm) :
    ownerfont = bitmap_font.load_font("Alef-Bold-18.bdf")  # 18 point bitmap font
    banner_text = label.Label(ownerfont, text=name, color=color)
    banner_text.x = int(((display.width - banner_text.bounding_box[2])/2)-1)
    banner_text.y = int(((display.height - banner_text.bounding_box[3])/2)+1)
    #banner_text.y = int((display.height / 2)-5)
    display.show(banner_text)
    display.refresh()
    if SHOW_IMG > 0 :
        time.sleep(hold)              # Display the name before the graphics
    else :
        if hold > init_tm :
            time.sleep(hold - init_tm)  # minus the initialization time if there are images
    # release memory
    del ownerfont
    del banner_text
    gc.collect()

def DisplayImage(img, hold, images, init_tm) :
    # Create the first image centered on the display
    try :
        bitmap, palette = adafruit_imageload.load(img, bitmap=displayio.Bitmap, palette=displayio.Palette)
    except:
        bitmap = displayio.OnDiskBitmap(img)
        palette = bitmap.pixel_shader
    x = int((display.width - bitmap.width) / 2)
    y = int((display.height - bitmap.height) / 2)
    if x < 0 : x = 0
    if y < 0 : y = 0
    tile_grid = displayio.TileGrid(bitmap, pixel_shader=palette, x=x, y=y)
    img = displayio.Group()
    img.append(tile_grid)
    display.show(img)
    display.refresh()
    if hold > init_tm :
        if images > 1 :
            time.sleep(hold)              # hold the first image before showing the second
        else :
            if hold > init_tm :
                time.sleep(hold - init_tm)  # minus the initialization time if there is 1 image
    img.pop()
    del bitmap
    del img
    del tile_grid
    gc.collect()

def GetBattPercent(batt_pin) :
    percent = 0
    # read the battery voltage (approximation, not exact levels with no fuel gauge to read)
    batt_volts = (batt_pin.value * 3.3) / 65536 * 2
    if batt_volts > 3.80 :
        percent = 86                    # 100% to 81% capacity
    elif batt_volts > 3.65 :
        percent = 50                    # 80%  to 31% capacity
    elif batt_volts > 3.40 :
        percent = 25                    # 30%  to 16% capacity
    else :
        percent = 5                     # 15%  to  0% capacity
    return percent

# Turn off the LCD Backlight
displayio.release_displays()

# Setup the bus, display object, and font for the display
if BOARD_TYPE == "PiPicoRP2040" :
    spi = busio.SPI(clock=board.GP10, MOSI=board.GP11, MISO=board.GP12)
else :
    spi = board.SPI()
while not spi.try_lock():
    pass
spi.configure(baudrate=SPI_SPEED)  # Configure SPI with the specified speed
spi.unlock()
if BOARD_TYPE == "FeatherM4" or BOARD_TYPE == "ESP32-S3" :
    tft_cs  = board.D6
    tft_dc  = board.D9
    lcd_rst = board.D5
    lcd_light = board.D10
elif BOARD_TYPE == "PiPicoRP2040" :
    tft_cs    = board.GP28
    tft_dc    = board.GP14
    lcd_rst   = board.GP27
    lcd_light = board.GP15
else:
    lcd_light = board.D10
    tft_cs = board.D2
    tft_dc  = board.D3
    lcd_rst = board.D4

display_bus = displayio.FourWire(spi, command=tft_dc, chip_select=tft_cs, baudrate=SPI_SPEED, reset=lcd_rst, polarity=0, phase=0)
if DISPLAY == "Pre-Beskar":
    display     = ST7789(display_bus, rotation=270, width=240, height=135, rowstart=40, colstart=53, auto_refresh=False, backlight_pin=lcd_light, brightness=0)
    font        = bitmap_font.load_font("mandalor135.bdf")  # 135 pixel tall bitmap font
    offset      = 12
elif DISPLAY == "Beskar":
    display     = ST7789(display_bus, rotation=0, width=240, height=240, rowstart=80, auto_refresh=False, backlight_pin=lcd_light, brightness=0)
    font        = bitmap_font.load_font("mandalor165.bdf")  # 165 pixel tall bitmap font
    offset      = 14
stage = displayio.Group()
display.show(stage)

# Disable WiFi power
if BOARD_TYPE == "ESP32-S3" :
    import wifi
    wifi.radio.enabled = 0

# Configure LEDs
if BOARD_TYPE == "ESP32-S3" :
    # setup the onboard neopixel LED power control
    led_pwr = digitalio.DigitalInOut(board.NEOPIXEL_POWER)
    led_pwr.direction = digitalio.Direction.OUTPUT

if BOARD_TYPE == "FeatherM4" or BOARD_TYPE == "ESP32-S3" or BOARD_TYPE == "ItsyBitsyRP2040" :
    led = neopixel.NeoPixel(board.NEOPIXEL, 1)
elif BOARD_TYPE == "ItsyBitsyM4" :
    led = dotstar.DotStar(board.APA102_SCK, board.APA102_MOSI, 1) # onboard dotstar
elif BOARD_TYPE == "PiPicoRP2040" :
    led = digitalio.DigitalInOut(board.LED)
    led.direction = digitalio.Direction.OUTPUT

if ENABLE_LEDS > 0 :
    if BOARD_TYPE != "PiPicoRP2040" :
        led.brightness = 0.05  # dim the LED to 5%
        led[0] = (255, 0, 255) # purple
    if BOARD_TYPE == "ESP32-S3" :
        led_pwr.value = True
else :
    if BOARD_TYPE != "PiPicoRP2040" :
        led.brightness = 0  # dim the LED to 0%
    if BOARD_TYPE == "ESP32-S3" :
        led_pwr.value = False

# Setup battery monitoring
if BATTERY_MON > 0 :
    lowbattX = 0
    lowbattY = 0
    vbat_voltage = 0
    if BOARD_TYPE == "ESP32-S3" :
        i2c = board.I2C()  # uses board.SCL and board.SDA
        sensor = LC709203F(i2c)
        sensor.PackSize = BATTERY_SZ
    elif BOARD_TYPE == "FeatherM4" :
        vbat_voltage = AnalogIn(board.VOLTAGE_MONITOR) # for measuring battery voltage
    elif BOARD_TYPE == "PiPicoRP2040" :
        # battery voltage measurements need a jumper from VSYS to ADC0 (pin 39 - 31)
        vbat_voltage = AnalogIn(board.GP26) # for measuring battery voltage
    elif BOARD_TYPE == "ItsyBitsyM4" or BOARD_TYPE == "ItsyBitsyRP2040" :
        # battery voltage measurements need a jumper from batt to A1
        vbat_voltage = AnalogIn(board.A1)

    # Create the second image centered on the display
    lowbattImg, lowbattPal = adafruit_imageload.load("LowBatt.bmp", bitmap=displayio.Bitmap, palette=displayio.Palette)
    x = int(display.width - lowbattImg.width)
    y = int(display.height - lowbattImg.height)
    if x < 0 : x = 0
    if y < 0 : y = 0
    lowbattX = x
    lowbattY = y
else :
    # Disable I2C port power
    if BOARD_TYPE == "ESP32-S3" :
        i2c_pwr = digitalio.DigitalInOut(board.I2C_POWER)
        i2c_pwr.direction = digitalio.Direction.OUTPUT
        i2c_pwr.value = False

# Turn on the Backlight
display.brightness = DISP_BRIGHT / 100
init_time = 4.5   # how long it takes to initialize the sequence

# Show the owner's name at startup
if SHOW_NAME > 0 :
    DisplayName(OWNER_NAME, NAME_HOLD, NAME_COLOR, init_time)

# Show the banner graphic(s)
if SHOW_IMG > 0 :
    DisplayImage(IMG1, IMG1_HOLD, SHOW_IMG, init_time)
    DisplayImage(IMG2, IMG2_HOLD, SHOW_IMG, init_time)

gc.collect()
low_batt_icon = 0
batt_percent  = 0

# Prepare the Mandalorian characters
text   = label.Label(font, text=messages[0], color=TEXT_COLOR)
text.x = int(((display.width - text.width)/2)-1)
text.y = int((display.height / 2)+offset)
if text.x < 0:
    text.x = 0
if text.y < 0:
    text.y = 0
stage.append(text)

# Initialize the low battery icon
if BATTERY_MON > 0 :
    batt_tile = displayio.TileGrid(lowbattImg, pixel_shader=lowbattPal, x=lowbattX, y=lowbattY)

display.show(stage)
while True:
    index = 0
    for msg in messages:
        text.text = msg
        display.refresh()
        if BOARD_TYPE == "PiPicoRP2040" :
            time.sleep(delays[index]* 0.75)
        else :
            time.sleep(delays[index])
        index = index + 1

    if BATTERY_MON > 0 :
        if BOARD_TYPE == "ESP32-S3" :
            sensor = LC709203F(i2c)
            batt_percent = sensor.cell_percent
        else :
            batt_percent = GetBattPercent(vbat_voltage)
        if batt_percent < LOW_BATT_LEVEL :
            # Add low battery icon
            if low_batt_icon == 0 :
                stage.append(batt_tile)
                low_batt_icon = 1
        else :
            if low_batt_icon > 0 :
                # Remove low battery icon
                stage.pop()
                low_batt_icon = 0

**Comment by Breazile** [comment]
Looks like you downloaded the wrong zip file (esp32). You need the zip for the feather m4 express.

https://github.com/Breazile/MandoPuter/blob/master/Releases/FeatherM4Beskar.zip

**Comment by AriadnaDRA** [comment]
Sorry I put the wrong link,  but the files are the correct ones

**Comment by Breazile** [comment]
It should look similar to this:

<img width="398" alt="image" src="https://github.com/Breazile/MandoPuter/assets/59380049/bc21b2a3-0547-4954-a28e-8e2f63aad632">

**Comment by AriadnaDRA** [comment]
i have this 
![image](https://github.com/Breazile/MandoPuter/assets/133783611/953ebcd8-f639-400f-84fd-404109657d8a)

**Comment by AriadnaDRA** [comment]
it's all the files from : 
https://github.com/Breazile/MandoPuter/blob/master/Releases/FeatherM4Beskar.zip 

All are almost the same but you have some files .wav that i dont have

**Comment by AriadnaDRA** [comment]
Sorry for being a pain in the ass, but it's frustrating me a little bit, I've continued investigating and I can't find anything else, and when I try the PuTTY again I only get a black screen and I don't understand anything TT

![image](https://github.com/Breazile/MandoPuter/assets/133783611/805ddcce-3f52-4757-aa7b-facbea66de5e)

**Comment by Breazile** [comment]
Been busy at work and headed out tomorrow to go camping. Things look right, so I'm going to try it on my board with Circuitpython 8.2.

In the meantime, you can try installing the Mu editor and load the code.py from your board while it is plugged in? If you click on the serial icon, it should spit out some error message at the bottom when it hits a problem. That would pinpoint where things are going wrong in the code. Details on installing Mu are here:

https://learn.adafruit.com/welcome-to-circuitpython/installing-mu-editor

**Comment by Breazile** [comment]
OK, I loaded CircuitPython 8.2 to my feather board. Then I erased all of the files from the circuitpy drive and copied over the contents of the ZIP file. It's running fine. You might try removing all files and copying again. If that fails then I think we need to look at the wiring

**Comment by Breazile** [comment]
Looking at your display it has no chip select pin like the other displays. Not clear if that is even needed, but one difference. I'm looking at the documentation to see if there are any code changes needed.

You can try changing the bit speed back to the default and see if that helps. This line here in config.py:

SPI_SPEED      = 48000000               # How fast the SPI bus to the LCD operates

Change the 48 to 24 and keep all of the zeros

**Comment by AriadnaDRA** [comment]
I installed the MU editor and change all you say but its still the same
![image](https://github.com/Breazile/MandoPuter/assets/133783611/e1e3f59a-ef74-479d-92e6-7a135987737d)

**Comment by AriadnaDRA** [comment]
I copy again the libraries carpet and now it seams to be caught in the output
![image](https://github.com/Breazile/MandoPuter/assets/133783611/65316cd8-1e99-4abe-bcb6-f21ab42628f2)

**Comment by Breazile** [comment]
I looked and the API only supports 4 wires (not 3). Not sure if that is a problem, especially if the wire is just an output to the display. I tried searching for the display specs but could not find it. I'm going camping, back on Wednesday. If I think of anything else to try I'll let you know. One thing you can do is turn on the debug LED. It should be purple if the code is running correctly

ENABLE_LEDS    = 0                      # Set to 1 to turn on LEDs for debugging, set to 0 to save battery

Change the 0 to 1

**Comment by AriadnaDRA** [comment]
Sorry for the delay but Im in a work trip and i forget the cable at home :')

I finally get one and i try the led and it shows in purple!
![WhatsApp Image 2023-07-18 at 6 23 35 PM](https://github.com/Breazile/MandoPuter/assets/133783611/2cb7c597-c674-4fbd-902b-2524c085baa1)

**Comment by Breazile** [comment]
OK, so the code is running which narrows things down a bit. Try setting the SPI_SPEED down to 24000000:

SPI_SPEED      = 48000000               # How fast the SPI bus to the LCD operates

Just change the 48 to a 24.

Another thing you can try is the phase and polarity settings (try changes one at a time):

display_bus = displayio.FourWire(spi, command=tft_dc, chip_select=tft_cs, baudrate=SPI_SPEED, reset=lcd_rst, polarity=0, phase=0)

On the line above try changing the polarity to 1, and phase to 1. There are 3 combinations to try:

polarity = 1, phase = 0
polarity = 0, phase = 1
polarity = 1, phase = 1

I would keep the SPI_SPEED at 24000000 when trying those since that is the default speed and it won't make a difference.

**Comment by AriadnaDRA** [comment]
OMG it works!!!

https://github.com/Breazile/MandoPuter/assets/133783611/43189b67-18a4-434f-b3f5-77dfa8abaa52

Thanks for all!! you are the best!

**Comment by Breazile** [comment]
Glad we finally got it working
