### ISSUE TITLE
Wiring for the IPS 1.3 SPI Display - ST7789

### ISSUE THREAD

**Issue by MandalorianoBrasil** [Breazile/MandoPuter#17]
I'm using a Raspberry Pi Pico and an IPS 1.3 SPI Display - ST7789, as they are the only products I found in Brazil.

However, the display pins are different, it has:
GND, VCC, SCL, SDA, RES, DC, BLK

I would like to know if you could help me connect this display to the board, and if I need to make any changes to the code.
Thanks.

![image](https://github.com/Breazile/MandoPuter/assets/147088197/fb926095-906a-4577-bbdd-541efa2cb459)
![image](https://github.com/Breazile/MandoPuter/assets/147088197/4dce3ed2-b2e5-46ba-a9e0-c9e5ecd7e1f4)

**Comment by Breazile** [comment]
I just saw this. Were you able to get it working? If not, please let me know.

**Comment by MandalorianoBrasil** [comment]
Hi Jon,

I managed to make it work based on your response in another ticket.

BLK pin should be the same as LITE
RES same as RST
SCL same as SCK
SDA same as SI

SPI_SPEED down to 24000000

and

polarity = 1, phase = 0

I would like to take this opportunity to say thank you very much for the project, I made a dream come true.

**Comment by Breazile** [comment]
Glad you got it working :)
