### ISSUE TITLE
Issue with display using Waveshare 1.3inch LCD Module

### ISSUE THREAD

**Issue by mikugenesys** [Breazile/MandoPuter#2]
Hello Breazile,
Im trying to wire up this Mandoputer and I've gotten to the point where i believe I've adjusted the code correctly and I've plugged all the pins in correctly(i think) but the LCD is not displaying. The backlight is coming on but nothing is there. Ill attach some pictures of what I have.

**Comment by mikugenesys** [comment]
![9FA4A2FD-C000-4D0D-9437-4E720355ADD7](https://user-images.githubusercontent.com/74171363/98507894-5b838100-2213-11eb-84c2-a79a72018d93.jpeg)
![5A6CD28B-8810-4C71-9FB9-06E63BC1AC8D](https://user-images.githubusercontent.com/74171363/98507903-5f170800-2213-11eb-88e4-8f260f057a3f.jpeg)
![D5A6E5B8-0361-42F6-812D-A45770D57289](https://user-images.githubusercontent.com/74171363/98507908-60e0cb80-2213-11eb-802b-3c9b110b496e.jpeg)
![1DB4F825-55E6-4DCC-BE5C-A67641B88226](https://user-images.githubusercontent.com/74171363/98507915-62aa8f00-2213-11eb-9813-7e2f9f01f14b.jpeg)

**Comment by Breazile** [comment]
It looks like the wiring is incorrect. Take a look at the diagram here: https://github.com/Breazile/MandoPuter/blob/master/Adafruit_1-14_Wiring.jpg

Here is the mapping of the pin names. Power looks OK since you have the backlight on.

DIN = MOSI
CLK = SCK
CS = TFTCS
DC = DC
RST = RST
BL = no connection

**Comment by Breazile** [comment]
Once you have the wiring done, check the LED on the feather board. The main LED goes purple for a while during initialization, and then turns solid red, yellow, or green depending upon your battery charge level. If you see a different pattern like flashing blue then we need to check the code. I ordered one of those LCDs in case I need to make a code change. I won't have it until December though.

**Comment by mikugenesys** [comment]
ok after checking al the connections again it seems to be doing the same thing. Im getting a cycle of colors on the LED and then it flashes blue and yellow.

**Comment by Breazile** [comment]
That flashing sequence (flashing blue) is an error sequence, and means one of three things:

1) Out of date CircuitPython
2) Missing files
3) Error in code.py

The latest CircuitPython is here: https://circuitpython.org/board/feather_m4_express/
Hit the reset button a couple of times on the Feather until you see the Featherboot drive appear. Then copy the UF2 file to it, and it will update CircuitPython. More detailed instructions here - https://learn.adafruit.com/adafruit-feather-m4-express-atsamd51/circuitpython

Once you have CircuitPython updated you should see a drive called Circuitpy enumerate. When you see that download the zip file and copy all of the files to the root of that drive - https://github.com/Breazile/MandoPuter/blob/master/MandoPuter.zip

At that point the code should run, and you should see the LED go purple while initializing, and then change to solid red, yellow, or green depending upon the battery level. Get to that point first before customizing code.py (it will work to some degree right out of the zip file). The LCD may come on, but the image will be cut off and in the wrong rotation.

Once you have the solid LED it means the code is working, and then you can customize code.py. You only need to select the Display type and rotation. The attached file should work for your setup.
[code.zip](https://github.com/Breazile/MandoPuter/files/5516482/code.zip)

**Comment by mikugenesys** [comment]
Hey that did it! For some reason when I edited the code it must have not allowed it to run. I noticed the image display never ran and in the code its labeled "Baby3_135x240.bmp" so i was originally changing it to "MudHorn240.bmp" with 240x240 picture on the feather. Not sure if this messed it up but i was wondering now how to display images like the mud horn.

**Comment by Breazile** [comment]
I'm glad you got it to work.
