### ISSUE TITLE
Typo on wiring table for Feather 

### ISSUE THREAD

**Issue by rmccaskill** [Breazile/MandoPuter#4]
**Describe the bug**
Wiring table, column 1 (Feather), row 3 - states to solder CLK to SCK on the LCD panel. However, the image below shows SCK on the feather being wired to SCK on the panel. As there is no CLK pin on the Feather, I assume the intention is to connect SCK to SCK.

**Expected behavior**
Connect pin SCK on the feather to SCK on the LCD

**Comment by Breazile** [comment]
Fixed, thanks.

**Comment by rmccaskill** [comment]
Thanks for the excellent tutorial!  Got it up and running in no time!
