### ISSUE TITLE
LCD display not displaying images.

### ISSUE THREAD

**Issue by acrylikhan** [Breazile/MandoPuter#5]
I am using the Feather M4 Express and the Adafruit 1.14 LCD screen. I could not get Circuit Python 4, so I had to install Version 6 on the Express. I have double checked that my wiring is correct, and my solder joints are solid, and made sure that I had the code properly adjusted for the M4 and the proper screen. I did not change anything else to the base code.

The weird: When the board was connected to the computer, the program runs great and LCD displays the rotating letters. As soon as I disconnected the feather from the computer, the display froze on the last three letters displayed. I hit the reset button and the screen went blank. The LCD screen has power and you can tell it is on. I disconnected the battery, let the feather rest for 10 minutes, before plugging the battery back in... still nothing will display on the monitor, but the monitor is on.

I wiped the feather and re installed everything to the letter on your instructional video, and it will not display anything on the screen. The only think I can think of is that you used Circuit Python 4, and I had no choice but to use Circuit Python 6. That is the only thing that could be the issue. Let me know what else I can try to get this to work. Thanks!

**Comment by Breazile** [comment]
CircuitPython 6 works just fine. Are you using an Adafruit battery? If not, try removing the battery and let it power through the USB port. If that works then your battery polarity is likely reversed.

**Comment by acrylikhan** [comment]
Yes, I am using the adafruit battery you recommended. I can check the polarity on that. I tried powering with just the usb and it still isn't displaying. I wired the 3V and the Ground like you did in your photograph of you holding the completed board in your hand. I noticed that the diagram for the Feather M4 Express has the 3V and the Ground further away from the USB port. Should I move the LCD power wires to the locations on the diagram I wonder if I have a faulty LCD screen?

**Comment by Breazile** [comment]
Send me a picture of the wiring if you can, and check out the new Troubleshooting section on the main page, particularly with the color of the onboard LED. The LED should go purple when you power the board, and then green, yellow, or red. Let's get the LED showing the right color first which means the code is running properly, then we will look at the LCD. If you are using a Feather M4 Express with the 1.14 that is the stock configuration so the code will work fine with no modification

**Comment by acrylikhan** [comment]
![20210120_064353](https://user-images.githubusercontent.com/77738899/105216460-33b86f80-5b18-11eb-8c5e-caf174fc0dd7.jpg)
![20210120_064342](https://user-images.githubusercontent.com/77738899/105216484-3d41d780-5b18-11eb-8766-3b14f659076a.jpg)
![20210120_064333](https://user-images.githubusercontent.com/77738899/105216509-4632a900-5b18-11eb-8eb5-6338de1a45f0.jpg)

I don't have pic of the pixel when the board wad powered up, but it was always green. I'llcheck out the troubleshooting section, too!

**Comment by Breazile** [comment]
Wiring looks OK. Plug it into your PC and try deleting everything from the CIRCUITPY drive, then download the ZIP file and extract everything again. I updated my board to CircuitPython 6.0.1 and it is working ok

**Comment by Breazile** [comment]
You can leave power where it is, or move the wires to the opposite end of the board. Both will work.

**Comment by acrylikhan** [comment]
I figured it out! The TFTCS contact on the LCD was messed up... not sure if it was poor manufacture or bad soldering by me. I switched out with another LCD and it works like a charm now! Sorry this was a trivial thing I should have noticed from the start.
