### ISSUE TITLE
Support for Feather 32U4 WITH RFM69

### ISSUE THREAD

**Issue by dannyc09** [Breazile/MandoPuter#8]
**Is your feature request related to a problem? Please describe.**
I'm hoping this set up can be used with a different feather rather than the m4 express.  I have the 32U4 WITH RFM69 left over from another project. 
**Describe the solution you'd like**
Set up for use with feather 32U4 WITH RFM69.

**Describe alternatives you've considered**

**Additional context**

**Comment by dannyc09** [comment]
Amazing, thank you!

**Comment by Breazile** [comment]
The updates are posted new, let me know if you have any suggestions

**Comment by dannyc09** [comment]
The one thing I have noticed is that the 0.96" LCD is now no longer listed.

Will this still work on a 0.96" screen?

**Comment by Breazile** [comment]
Which 0.96" are you using? This one? https://www.adafruit.com/product/3533
Also, which controller board?

I can add display support, but removed many of them for now.

**Comment by dannyc09** [comment]
Yeah I'm using that one with the itsybitsy rp2040.

**Comment by Breazile** [comment]
I'll add the code there and the wiring is the same. The resolution is low compared to the other displays so it will need new fonts

**Comment by dannyc09** [comment]
That's great, thank you.  I'll give it a try tonight!

**Comment by Breazile** [comment]
Give this a try

https://github.com/Breazile/MandoPuter/blob/master/Releases/ItsyBitsyRP2040-096.zip

**Comment by dannyc09** [comment]
Absolutely perfect.

Thank you so much for helping with this and for your amazingly speedy response.

This set up is fantastic!
